name: Mirror to HF Space

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-space
  cancel-in-progress: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}  # Token HF con permiso Write
          HF_SPACE_REPO: ${{ vars.HF_SPACE_REPO }} # p.ej. Barearojojuan/MonoAgent
        run: |
          if [ -z "$HF_SPACE_REPO" ]; then
            HF_SPACE_REPO="Barearojojuan/MonoAgent"
          fi
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"

          # Añade remote autenticado (el token NO aparece en logs)
          HF_URL="https://user:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE_REPO}"
          git remote add hf "${HF_URL}" || git remote set-url hf "${HF_URL}"

          # Sube solo la rama main; --force para mantener espejo exacto si cambias historial
          git push hf HEAD:main --force
