name: Mirror to HF Space

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-space
  cancel-in-progress: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Space (ignoring model artifacts)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_REPO: ${{ vars.HF_SPACE_REPO }}
        shell: bash
        run: |
          set -euo pipefail

          if [ -z "${HF_SPACE_REPO:-}" ]; then
            HF_SPACE_REPO="Barearojojuan/MonoAgent"
          fi

          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"

          HF_URL="https://user:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE_REPO}"
          if git remote get-url hf >/dev/null 2>&1; then
            git remote set-url hf "${HF_URL}"
          else
            git remote add hf "${HF_URL}"
          fi

          # --- quitar SOLO los dos archivos grandes del índice ---
          git rm --cached -f model/labels.json || true
          git rm --cached -f model/monkey_classifier_ts-v0.1.pt || true

          # Empujar rama main (el resto de archivos sí se suben)
          git push hf HEAD:main --force
