name: Mirror to HF Space

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-space
  cancel-in-progress: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push code to HF Space (exclude 2 model files)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}        # token con Write al Space
          HF_SPACE_REPO: ${{ vars.HF_SPACE_REPO }} # ej: Barearojojuan/MonoAgent
        shell: bash
        run: |
          set -euo pipefail

          if [ -z "${HF_SPACE_REPO:-}" ]; then
            HF_SPACE_REPO="Barearojojuan/MonoAgent"
          fi

          # 1) Construir snapshot limpia EXCLUYENDO solo esos dos archivos
          rm -rf _space_out
          mkdir -p _space_out

          rsync -a ./ _space_out \
            --exclude '.git' \
            --exclude 'model/labels.json' \
            --exclude 'model/monkey_classifier_ts-v0.1.pt'

          # 2) Inicializar repo temporal y commitear
          cd _space_out
          git init
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          git add -A
          git commit -m "Deploy code (excluding model/labels.json and model/monkey_classifier_ts-v0.1.pt)"

          # 3) Empujar esta instantánea al Space como main
          HF_URL="https://user:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE_REPO}"
          git remote add origin "${HF_URL}"
          git branch -M main
          git push origin main --force
